# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ram_generator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ram_generator.proto\x12\rram_generator\"1\n\x1aGenerateStartPromptRequest\x12\x13\n\x0buser_prompt\x18\x01 \x01(\t\"0\n\x1bGenerateHybridPromptRequest\x12\x11\n\tram_image\x18\x01 \x03(\t\"\x1d\n\x0bImagePrompt\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"5\n\x14GenerateImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05style\x18\x02 \x01(\t\"*\n\x15GenerateImageResponse\x12\x11\n\tram_image\x18\x01 \x01(\t2\xa8\x02\n\x0cRamGenerator\x12\\\n\x13GenerateStartPrompt\x12).ram_generator.GenerateStartPromptRequest\x1a\x1a.ram_generator.ImagePrompt\x12^\n\x14GenerateHybridPrompt\x12*.ram_generator.GenerateHybridPromptRequest\x1a\x1a.ram_generator.ImagePrompt\x12Z\n\rGenerateImage\x12#.ram_generator.GenerateImageRequest\x1a$.ram_generator.GenerateImageResponseB3Z1github.com/KalashnikovProjects/RamGenerator/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ram_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/KalashnikovProjects/RamGenerator/proto'
  _globals['_GENERATESTARTPROMPTREQUEST']._serialized_start=38
  _globals['_GENERATESTARTPROMPTREQUEST']._serialized_end=87
  _globals['_GENERATEHYBRIDPROMPTREQUEST']._serialized_start=89
  _globals['_GENERATEHYBRIDPROMPTREQUEST']._serialized_end=137
  _globals['_IMAGEPROMPT']._serialized_start=139
  _globals['_IMAGEPROMPT']._serialized_end=168
  _globals['_GENERATEIMAGEREQUEST']._serialized_start=170
  _globals['_GENERATEIMAGEREQUEST']._serialized_end=223
  _globals['_GENERATEIMAGERESPONSE']._serialized_start=225
  _globals['_GENERATEIMAGERESPONSE']._serialized_end=267
  _globals['_RAMGENERATOR']._serialized_start=270
  _globals['_RAMGENERATOR']._serialized_end=566
# @@protoc_insertion_point(module_scope)
