version: 3.0

ports:
  go_static_server: 8081
  go_api: 8082

prompts:
  base_start_prompt: 'Ты пишешь промты для генерации баранов с помощью нейросети Kandinsky на основе запроса
пользователя. Ты не имеешь право задавать в промпте параметры чего-либо кроме внешнего
вида барана. Помимо требований пользователя ты должен добавить
от себя 1 случайный признак для барана. (мутацию)'
  base_hybrid_prompt: 'Ты пишешь промт для нейросети Kandinsky на основе запроса пользователя и описания баранов в стаде. 
Нейросеть для генерации изображений рисует различных баранов, ты не имеешь право задавать в промпте параметры чего-либо кроме внешнего 
вида барана. Ты пишешь промпт на основе запроса пользователя и в большей степени на основе описания других его баранов, ты должен добавить ровно
1 случайный признак от себя (мутацию), всё остальное на основе запроса или других баранов.'
  base_image_prompt: "баран, баран на переднем плане, "
  negative_image_prompt: "яркие цвета, кислотность, высокая контрастность"
  base_description_prompt: "Напиши максимально кратное описание барана на этом изображении (не более 6 слов)."

clicks:
  first_ram: 100
  daily_rams:
    - 200
    - 500

gemini:
  model: "models/gemini-1.5-flash-latest"
  rate_limit: 15
  max_response_length: 50
  proxy: true
  proxy_endpoint: "cheery-baklava-3e2f26.netlify.app"
  proxy_transport: "rest"

users:
  default_avatar: "/static/img/default-avatar.png"
  default_avatar_box:
    - [0.05, 0.25]
    - [0.55, 0.75]
  max_username_len: 24

generation:
  max_prompt_len: 30
  time_between_daily: 1200
  time_between_daily_another:
    - 10

image:
  side: 400
  kandinsky_endpoint: "https://api-key.fusionbrain.ai/"
  default_kandinsky_style: "DEFAULT"

websocket:
  ping_period: 3
  pong_wait:   5
