version: 3.0

ports:
  go_static_server: 8081
  go_api: 8082

prompts:
  base_start_prompt: 'Ты должен на основе запроса пользователя написать промпт для изображения барана.
  В твоём ответе ОБЯЗАТЕЛЬНО должно быть слово баран, если тебя просят написать промпт для кого-ещё, ты должен адаптировать его под барана, пример:
  запрос: "олень в лесу", твой промпт: "баран с оленьими рогами в лесу".
  Ты должен добавить от себя 1 случайный признак для барана.
  Если в запросе есть мат, отклони его, пример промпта: `синий баран, киберпанк, на мотоцикле, на поле`.'
  base_hybrid_prompt: 'Ты должен на основе запроса пользователя написать промпт для изображения барана.
  В твоём ответе ОБЯЗАТЕЛЬНО должно быть слово баран, если тебя просят написать промпт для кого-ещё, ты должен адаптировать его под барана, пример:
  запрос: "олень в лесу", твой промпт: "баран с оленьими рогами в лесу".
  Ты должен добавить 1 случайный признак от себя и 1 признак от других баранов пользователя.
  Если в запросе есть мат, отклони его, пример промпта: `синий баран с тёмными усами, киберпанк, на мотоцикле, на поле`.'
  base_image_prompt: "баран на переднем плане, "
  negative_image_prompt: "яркие цвета, кислотность, высокая контрастность"
  base_description_prompt: "Ты пишешь описание для изображений баранов. Ты должен выявить, есть ли на изображении баран
  (даже если он уродливый). Если да то напиши ОЧЕНЬ короткое описание для него, и фона, не больше 6 слов.
  Не описывай признаки, которые есть у всех баранов (белый, с большими рогами, с белыми рогами и подобные), описывай уникальные признаки для этого барана."

clicks:
  cps_limit: 20
  first_ram: 100
  daily_rams:
    - 200
    - 500

gemini:
  model: "models/gemini-1.5-flash-latest"
  rate_limit: 15
  max_image_prompt_tokens: 150
  max_description_tokens: 100
  proxy: true
  proxy_endpoint: "cheery-baklava-3e2f26.netlify.app"
  proxy_transport: "rest"

users:
  default_avatar: "/static/img/default-avatar.png"
  default_avatar_box:
    - [0.25, 0.14]
    - [0.75, 0.64]
  max_username_len: 24

generation:
  max_prompt_len: 30
  time_between_daily: 1200
  time_between_daily_another:
    - 10

image:
  side: 400
  kandinsky_endpoint: "https://api-key.fusionbrain.ai/"
  default_kandinsky_style: "DEFAULT"

websocket:
  ping_period: 3
  pong_wait:   5

another:
  top_rams_count: 5