version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go-rest:
    build:
      context: Backend/Go
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOSTNAME: postgres
      GRPC_HOSTNAME: pygrpc
    ports:
      - "80:80"
    depends_on:
      - postgres

  py-grpc:
    hostname: pygrpc
    build:
      context: Backend/Python
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GRPC_HOSTNAME: pygrpc
    ports:
      - "50051:50051"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"


volumes:
  postgres:
  pgadmin: