version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpasswordalo"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"