version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-api
      - go-static-server

  postgres:
    image: postgres
    hostname: postgres
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go-api:
    hostname: api
    build:
      context: /
      dockerfile: Backend/Go-api/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres:5432
      GRPC_HOST: python-ai:50051
    ports:
      - "8082:8082"
    depends_on:
      - python-ai
      - postgres

  go-static-server:
    hostname: static-server
    build:
      context: /
      dockerfile: Backend/Go-static-server/Dockerfile
    ports:
      - "8081:8081"

  python-ai:
    hostname: pygrpc
    build:
      context: /
      dockerfile: Backend/Python-ai/Dockerfile
    env_file:
      - .env
    environment:
      GRPC_PORT: 50051
      GRPC_HOST: python-ai:50051
    ports:
      - "50051:50051"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"


volumes:
  postgres:
  pgadmin: