version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go-rest:
    build:
      dockerfile: Docker/go-rest.Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  py-grpc:
    build:
      dockerfile: Docker/py-grpc.Dockerfile
    env_file:
      - .env
    ports:
      - "50051:50051"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"


volumes:
  postgres:
  pgadmin: