# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ram_generator_pb2 as ram__generator__pb2


class RamGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStartPrompt = channel.unary_unary(
                '/ram_generator.RamGenerator/GenerateStartPrompt',
                request_serializer=ram__generator__pb2.GenerateStartPromptRequest.SerializeToString,
                response_deserializer=ram__generator__pb2.RamImagePrompt.FromString,
                )
        self.GenerateHybridPrompt = channel.unary_unary(
                '/ram_generator.RamGenerator/GenerateHybridPrompt',
                request_serializer=ram__generator__pb2.GenerateHybridPromptRequest.SerializeToString,
                response_deserializer=ram__generator__pb2.RamImagePrompt.FromString,
                )
        self.GenerateImage = channel.unary_unary(
                '/ram_generator.RamGenerator/GenerateImage',
                request_serializer=ram__generator__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=ram__generator__pb2.RamImage.FromString,
                )
        self.GenerateDescription = channel.unary_unary(
                '/ram_generator.RamGenerator/GenerateDescription',
                request_serializer=ram__generator__pb2.RamImageUrl.SerializeToString,
                response_deserializer=ram__generator__pb2.RamDescription.FromString,
                )


class RamGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateStartPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHybridPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RamGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateStartPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStartPrompt,
                    request_deserializer=ram__generator__pb2.GenerateStartPromptRequest.FromString,
                    response_serializer=ram__generator__pb2.RamImagePrompt.SerializeToString,
            ),
            'GenerateHybridPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHybridPrompt,
                    request_deserializer=ram__generator__pb2.GenerateHybridPromptRequest.FromString,
                    response_serializer=ram__generator__pb2.RamImagePrompt.SerializeToString,
            ),
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=ram__generator__pb2.GenerateImageRequest.FromString,
                    response_serializer=ram__generator__pb2.RamImage.SerializeToString,
            ),
            'GenerateDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDescription,
                    request_deserializer=ram__generator__pb2.RamImageUrl.FromString,
                    response_serializer=ram__generator__pb2.RamDescription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ram_generator.RamGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RamGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateStartPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ram_generator.RamGenerator/GenerateStartPrompt',
            ram__generator__pb2.GenerateStartPromptRequest.SerializeToString,
            ram__generator__pb2.RamImagePrompt.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateHybridPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ram_generator.RamGenerator/GenerateHybridPrompt',
            ram__generator__pb2.GenerateHybridPromptRequest.SerializeToString,
            ram__generator__pb2.RamImagePrompt.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ram_generator.RamGenerator/GenerateImage',
            ram__generator__pb2.GenerateImageRequest.SerializeToString,
            ram__generator__pb2.RamImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ram_generator.RamGenerator/GenerateDescription',
            ram__generator__pb2.RamImageUrl.SerializeToString,
            ram__generator__pb2.RamDescription.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
