# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ram_generator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ram_generator.proto\x12\rram_generator\"1\n\x1aGenerateStartPromptRequest\x12\x13\n\x0buser_prompt\x18\x01 \x01(\t\"L\n\x1bGenerateHybridPromptRequest\x12\x13\n\x0buser_prompt\x18\x01 \x01(\t\x12\x18\n\x10ram_descriptions\x18\x02 \x03(\t\" \n\x0eRamImagePrompt\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"5\n\x14GenerateImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05style\x18\x02 \x01(\t\"\x19\n\x08RamImage\x12\r\n\x05image\x18\x01 \x01(\t\"\x1a\n\x0bRamImageUrl\x12\x0b\n\x03url\x18\x01 \x01(\t\"%\n\x0eRamDescription\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t2\xf3\x02\n\x0cRamGenerator\x12_\n\x13GenerateStartPrompt\x12).ram_generator.GenerateStartPromptRequest\x1a\x1d.ram_generator.RamImagePrompt\x12\x61\n\x14GenerateHybridPrompt\x12*.ram_generator.GenerateHybridPromptRequest\x1a\x1d.ram_generator.RamImagePrompt\x12M\n\rGenerateImage\x12#.ram_generator.GenerateImageRequest\x1a\x17.ram_generator.RamImage\x12P\n\x13GenerateDescription\x12\x1a.ram_generator.RamImageUrl\x1a\x1d.ram_generator.RamDescriptionB4Z2github.com/KalashnikovProjects/RamGenerator/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ram_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/KalashnikovProjects/RamGenerator/protos'
  _globals['_GENERATESTARTPROMPTREQUEST']._serialized_start=38
  _globals['_GENERATESTARTPROMPTREQUEST']._serialized_end=87
  _globals['_GENERATEHYBRIDPROMPTREQUEST']._serialized_start=89
  _globals['_GENERATEHYBRIDPROMPTREQUEST']._serialized_end=165
  _globals['_RAMIMAGEPROMPT']._serialized_start=167
  _globals['_RAMIMAGEPROMPT']._serialized_end=199
  _globals['_GENERATEIMAGEREQUEST']._serialized_start=201
  _globals['_GENERATEIMAGEREQUEST']._serialized_end=254
  _globals['_RAMIMAGE']._serialized_start=256
  _globals['_RAMIMAGE']._serialized_end=281
  _globals['_RAMIMAGEURL']._serialized_start=283
  _globals['_RAMIMAGEURL']._serialized_end=309
  _globals['_RAMDESCRIPTION']._serialized_start=311
  _globals['_RAMDESCRIPTION']._serialized_end=348
  _globals['_RAMGENERATOR']._serialized_start=351
  _globals['_RAMGENERATOR']._serialized_end=722
# @@protoc_insertion_point(module_scope)
