// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: ram_generator.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateStartPromptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserPrompt string `protobuf:"bytes,1,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`
}

func (x *GenerateStartPromptRequest) Reset() {
	*x = GenerateStartPromptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ram_generator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateStartPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStartPromptRequest) ProtoMessage() {}

func (x *GenerateStartPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ram_generator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStartPromptRequest.ProtoReflect.Descriptor instead.
func (*GenerateStartPromptRequest) Descriptor() ([]byte, []int) {
	return file_ram_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateStartPromptRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

type GenerateHybridPromptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserPrompt string   `protobuf:"bytes,1,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`
	RamImages  []string `protobuf:"bytes,2,rep,name=ram_images,json=ramImages,proto3" json:"ram_images,omitempty"` // base64
}

func (x *GenerateHybridPromptRequest) Reset() {
	*x = GenerateHybridPromptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ram_generator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateHybridPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHybridPromptRequest) ProtoMessage() {}

func (x *GenerateHybridPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ram_generator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHybridPromptRequest.ProtoReflect.Descriptor instead.
func (*GenerateHybridPromptRequest) Descriptor() ([]byte, []int) {
	return file_ram_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateHybridPromptRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *GenerateHybridPromptRequest) GetRamImages() []string {
	if x != nil {
		return x.RamImages
	}
	return nil
}

type ImagePrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *ImagePrompt) Reset() {
	*x = ImagePrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ram_generator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagePrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePrompt) ProtoMessage() {}

func (x *ImagePrompt) ProtoReflect() protoreflect.Message {
	mi := &file_ram_generator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePrompt.ProtoReflect.Descriptor instead.
func (*ImagePrompt) Descriptor() ([]byte, []int) {
	return file_ram_generator_proto_rawDescGZIP(), []int{2}
}

func (x *ImagePrompt) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GenerateImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Style  string `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ram_generator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ram_generator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_ram_generator_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateImageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateImageRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RamImage string `protobuf:"bytes,1,opt,name=ram_image,json=ramImage,proto3" json:"ram_image,omitempty"` // base64
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ram_generator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ram_generator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_ram_generator_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateImageResponse) GetRamImage() string {
	if x != nil {
		return x.RamImage
	}
	return ""
}

var File_ram_generator_proto protoreflect.FileDescriptor

var file_ram_generator_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x61, 0x6d, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x61, 0x6d, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x22, 0x3d, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x22, 0x5d, 0x0a, 0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x48,
	0x79, 0x62, 0x72, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x6d, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x61, 0x6d, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x44, 0x0a, 0x14, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x22,
	0x34, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x6d, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x61, 0x6d,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x32, 0xa8, 0x02, 0x0a, 0x0c, 0x52, 0x61, 0x6d, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x29, 0x2e,
	0x72, 0x61, 0x6d, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x61, 0x6d, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x12, 0x5e, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x48, 0x79, 0x62, 0x72, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x2a, 0x2e, 0x72,
	0x61, 0x6d, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x48, 0x79, 0x62, 0x72, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x61, 0x6d, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x12, 0x5a, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x72, 0x61, 0x6d, 0x5f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x61, 0x6d,
	0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b,
	0x61, 0x6c, 0x61, 0x73, 0x68, 0x6e, 0x69, 0x6b, 0x6f, 0x76, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x2f, 0x52, 0x61, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ram_generator_proto_rawDescOnce sync.Once
	file_ram_generator_proto_rawDescData = file_ram_generator_proto_rawDesc
)

func file_ram_generator_proto_rawDescGZIP() []byte {
	file_ram_generator_proto_rawDescOnce.Do(func() {
		file_ram_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_ram_generator_proto_rawDescData)
	})
	return file_ram_generator_proto_rawDescData
}

var file_ram_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ram_generator_proto_goTypes = []interface{}{
	(*GenerateStartPromptRequest)(nil),  // 0: ram_generator.GenerateStartPromptRequest
	(*GenerateHybridPromptRequest)(nil), // 1: ram_generator.GenerateHybridPromptRequest
	(*ImagePrompt)(nil),                 // 2: ram_generator.ImagePrompt
	(*GenerateImageRequest)(nil),        // 3: ram_generator.GenerateImageRequest
	(*GenerateImageResponse)(nil),       // 4: ram_generator.GenerateImageResponse
}
var file_ram_generator_proto_depIdxs = []int32{
	0, // 0: ram_generator.RamGenerator.GenerateStartPrompt:input_type -> ram_generator.GenerateStartPromptRequest
	1, // 1: ram_generator.RamGenerator.GenerateHybridPrompt:input_type -> ram_generator.GenerateHybridPromptRequest
	3, // 2: ram_generator.RamGenerator.GenerateImage:input_type -> ram_generator.GenerateImageRequest
	2, // 3: ram_generator.RamGenerator.GenerateStartPrompt:output_type -> ram_generator.ImagePrompt
	2, // 4: ram_generator.RamGenerator.GenerateHybridPrompt:output_type -> ram_generator.ImagePrompt
	4, // 5: ram_generator.RamGenerator.GenerateImage:output_type -> ram_generator.GenerateImageResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ram_generator_proto_init() }
func file_ram_generator_proto_init() {
	if File_ram_generator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ram_generator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateStartPromptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ram_generator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateHybridPromptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ram_generator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagePrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ram_generator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ram_generator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ram_generator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ram_generator_proto_goTypes,
		DependencyIndexes: file_ram_generator_proto_depIdxs,
		MessageInfos:      file_ram_generator_proto_msgTypes,
	}.Build()
	File_ram_generator_proto = out.File
	file_ram_generator_proto_rawDesc = nil
	file_ram_generator_proto_goTypes = nil
	file_ram_generator_proto_depIdxs = nil
}
